version: '3.8'

services:
  AI:
    image: torchserver
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    working_dir: /lab
    volumes:
      - ./:/lab
    ports:
      - "8888:8888"
